[package]
name = "IncognitoBin_worker"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
serde_json = "1.0.0"
serde = { version = "1.0.0", features = ["derive"] }
chrono = "0.4"
actix-web = "4"
redis = "0.27.2"
